# Model Configuration

# Random Forest Parameters
random_forest:
  n_estimators: [50, 100, 200]
  max_depth: [10, 20, 30, null]
  min_samples_split: [2, 5, 10]
  min_samples_leaf: [1, 2, 4]

# Gradient Boosting Parameters
gradient_boost:
  n_estimators: [50, 100, 200]
  learning_rate: [0.01, 0.1, 0.2]
  max_depth: [3, 5, 7]
  min_samples_split: [2, 5, 10]

# Linear Regression (no hyperparameters)
linear: {}

# Training Configuration
training:
  test_size: 0.2
  random_state: 42
  cv_folds: 3
  n_iter: 10

# Feature Engineering
features:
  use_pca: false
  use_polynomial: false
  n_components: 5
  poly_degree: 2